#BOARD_TAG=uno
BOARD_TAG=pro
BOARD_SUB=16MHzatmega328
ARDUINO_LIBS = RGB Stripper Adafruit_NeoPixel Adafruit_WS2801 SoftTimer RGBRamp SPI Bug
#include ../../Arduino.mk
include $(ARDMK_DIR)/Arduino.mk
