# these two need to be defined for 5V pro mini board
BOARD_TAG=pro
BOARD_SUB=16MHzatmega328
# only this for uno
#BOARD_TAG=uno
ARDUINO_LIBS = SoftTimer General Servo
#include ../../Arduino.mk
include $(ARDMK_DIR)/Arduino.mk
